// Calories burned per minute for an average 70kg (154lb) person
const activityDatabase = [
    { name: "Walking (Leisure, 3mph)", calPerMin: 3.5 },
    { name: "Walking (Brisk, 4mph)", calPerMin: 5.0 },
    { name: "Running (5mph / 12min mile)", calPerMin: 9.5 },
    { name: "Running (6mph / 10min mile)", calPerMin: 11.5 },
    { name: "Running (8mph / 7.5min mile)", calPerMin: 15.0 },
    { name: "Cycling (Leisure, 10mph)", calPerMin: 5.0 },
    { name: "Cycling (Moderate, 12-14mph)", calPerMin: 9.5 },
    { name: "Cycling (Vigorous, 16-19mph)", calPerMin: 14.0 },
    { name: "Swimming (Freestyle, Light)", calPerMin: 7.0 },
    { name: "Swimming (Freestyle, Vigorous)", calPerMin: 11.5 },
    { name: "Yoga", calPerMin: 3.0 },
    { name: "Pilates", calPerMin: 3.5 },
    { name: "Weightlifting (Light/Moderate)", calPerMin: 3.5 },
    { name: "Weightlifting (Vigorous)", calPerMin: 7.0 },
    { name: "HIIT (High Intensity Interval Training)", calPerMin: 10.0 },
    { name: "Aerobics (High Impact)", calPerMin: 8.0 },
    { name: "Dancing (General)", calPerMin: 5.0 },
    { name: "Basketball (Game)", calPerMin: 9.5 },
    { name: "Soccer (Competitive)", calPerMin: 11.5 },
    { name: "Tennis (Singles)", calPerMin: 9.0 },
    { name: "Tennis (Doubles)", calPerMin: 5.5 },
    { name: "Golf (Walking, Carrying Clubs)", calPerMin: 5.0 },
    { name: "Hiking", calPerMin: 7.0 },
    { name: "Jump Rope (Moderate)", calPerMin: 11.5 },
    { name: "Jump Rope (Fast)", calPerMin: 14.0 },
    { name: "Rowing Machine (Moderate)", calPerMin: 8.0 },
    { name: "Rowing Machine (Vigorous)", calPerMin: 10.0 },
    { name: "Stair Climber", calPerMin: 10.5 },
    { name: "Elliptical Trainer", calPerMin: 8.5 },
    { name: "House Cleaning", calPerMin: 3.0 },
    { name: "Gardening", calPerMin: 4.5 },
    { name: "Sleeping", calPerMin: 1.0 },
    { name: "Sitting/Working at Desk", calPerMin: 1.5 }
];
