const foodDatabase = [
    { name: "Apple", calories: 95, unit: "1 medium" },
    { name: "Banana", calories: 105, unit: "1 medium" },
    { name: "Chicken Breast", calories: 165, unit: "100g" },
    { name: "White Rice", calories: 130, unit: "100g cooked" },
    { name: "Brown Rice", calories: 112, unit: "100g cooked" },
    { name: "Egg", calories: 78, unit: "1 large" },
    { name: "Oatmeal", calories: 150, unit: "1/2 cup dry" },
    { name: "Salmon", calories: 206, unit: "100g" },
    { name: "Avocado", calories: 240, unit: "1 medium" },
    { name: "Almonds", calories: 164, unit: "1 oz (28g)" },
    { name: "Peanut Butter", calories: 190, unit: "2 tbsp" },
    { name: "Whole Wheat Bread", calories: 69, unit: "1 slice" },
    { name: "White Bread", calories: 75, unit: "1 slice" },
    { name: "Milk (Whole)", calories: 150, unit: "1 cup" },
    { name: "Milk (Skim)", calories: 83, unit: "1 cup" },
    { name: "Greek Yogurt", calories: 100, unit: "170g" },
    { name: "Cheese (Cheddar)", calories: 113, unit: "1 slice" },
    { name: "Broccoli", calories: 55, unit: "1 cup" },
    { name: "Spinach", calories: 7, unit: "1 cup raw" },
    { name: "Potato", calories: 161, unit: "1 medium baked" },
    { name: "Sweet Potato", calories: 103, unit: "1 medium baked" },
    { name: "Pizza (Cheese)", calories: 285, unit: "1 slice" },
    { name: "Burger (Fast Food)", calories: 250, unit: "1 burger" },
    { name: "French Fries", calories: 312, unit: "1 medium order" },
    { name: "Pasta", calories: 131, unit: "100g cooked" },
    { name: "Olive Oil", calories: 119, unit: "1 tbsp" },
    { name: "Orange", calories: 62, unit: "1 medium" },
    { name: "Grapes", calories: 62, unit: "1/2 cup" },
    { name: "Strawberries", calories: 49, unit: "1 cup" },
    { name: "Blueberries", calories: 84, unit: "1 cup" },
    { name: "Tomato", calories: 22, unit: "1 medium" },
    { name: "Cucumber", calories: 16, unit: "1 cup sliced" },
    { name: "Carrot", calories: 25, unit: "1 medium" },
    { name: "Onion", calories: 44, unit: "1 medium" },
    { name: "Garlic", calories: 4, unit: "1 clove" },
    { name: "Coffee (Black)", calories: 2, unit: "1 cup" },
    { name: "Tea (Unsweetened)", calories: 2, unit: "1 cup" },
    { name: "Soda", calories: 140, unit: "1 can (12 oz)" },
    { name: "Beer", calories: 153, unit: "1 can (12 oz)" },
    { name: "Wine (Red)", calories: 125, unit: "5 oz" },
    { name: "Chocolate (Dark)", calories: 170, unit: "1 oz" },
    { name: "Ice Cream (Vanilla)", calories: 137, unit: "1/2 cup" },
    { name: "Honey", calories: 64, unit: "1 tbsp" },
    { name: "Sugar", calories: 49, unit: "1 tbsp" },
    { name: "Salt", calories: 0, unit: "1 tsp" }
];
